// Generated by CoffeeScript 1.10.0
(function() {
  this.printTopic = function(title, msg) {
    document.getElementById("title").innerHTML += title;
    return document.getElementById("question").innerHTML += msg;
  };

  this.printAnswer = function(msg, name, speciality, city) {
    return document.getElementById("topic").innerHTML += "<div class=\"post\">\n        <div class=\"user\">\n                <img></img>\n                <div>\n                        <span class=\"username\">" + name + "</span>\n                        <span class=\"speciality\">" + speciality + "</span>\n                        <span class=\"city\">" + city + "</span>\n                </div>\n        </div>\n\n        <div class=\"answer\">" + msg + "</div>\n</div>";
  };

  printTopic("Title", "Pergunta");

  printAnswer("MSG1", "User1", "Pediatra", "Seattle");
  printAnswer("MSG2", "User2", "Clinico", "Alvorada");
  printAnswer("MSG3", "User3", "Psicologo", "POA");

}).call(this);

document.getElementById('submit').addEventListener("click", function() {
	var xhr = new XMLHttpRequest();
	var url = "url";
	xhr.open("POST", url, true);
	xhr.setRequestHeader("Content-Type", "application/json");
	xhr.onreadystatechange = function () {
		if (xhr.readyState === 4 && xhr.status === 200) {
			var json = JSON.parse(xhr.responseText);
			console.log(xhr.responseText);
		}
	};
	var data = JSON.stringify({"email": "hey@mail.com", "password": "101010"});
	xhr.send(data);

});
